version: '3.4'

services:
  teledoctestdb:
    container_name: teledoctestdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=TeledocTestDb
    restart: always
    ports:
      - "5432:5432" 
    volumes:
      - postgres_teledoc:/var/lib/postresql/data/

  teledoctest.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Database=Server=teledoctestdb;Port=5432;Database=TeledocTestDb;User Id=postgres;Password=postgres; 
    depends_on:
      - teledoctestdb
    ports:
      - "4040:8080"
      - "4041:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
